// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "../src/App.bs.js";
import * as Vitest from "rescript-vitest/src/Vitest.bs.js";
import * as Vitest$1 from "vitest";
import * as JsxRuntime from "react/jsx-runtime";
import * as React from "@testing-library/react";

Vitest.testAsync("renders component without crashing", undefined, (async function (t) {
        t.assertions(1);
        React.render(JsxRuntime.jsx(App.make, {}));
        await React.screen.findByText("Hello Vite + React + ReScript!");
        Vitest$1.expect(React.screen.getByText("count is: 0")).toBeInTheDocument();
      }));

export {
  
}
/*  Not a pure module */
