// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Billing(props) {
  return JsxRuntime.jsx("div", {
              children: "Billing"
            });
}

var make = Billing;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
