// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.bs.js";
import * as Styles from "../Styles.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Business(props) {
  return JsxRuntime.jsx("section", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("h2", {
                            children: [
                              "You do the business, ",
                              JsxRuntime.jsx("br", {
                                    className: "sm:block hidden"
                                  }),
                              "we'll handle the money."
                            ],
                            className: "" + Styles.styles.heading2 + ""
                          }),
                      JsxRuntime.jsx("p", {
                            children: "With the right credit card, you can improve your financial life by building credit, earning rewards and saving money. But with hundreds of credit cards on the market.",
                            className: "" + Styles.styles.paragraph + " max-w-[470px] mt-5"
                          }),
                      JsxRuntime.jsx("div", {
                            className: "mt-10"
                          }),
                      JsxRuntime.jsx(Button.make, {})
                    ],
                    className: "" + Styles.layout.sectionInfo + ""
                  })
            });
}

var make = Business;

export {
  make ,
}
/* Button Not a pure module */
