// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Business(props) {
  return JsxRuntime.jsx("div", {
              children: "Business"
            });
}

var make = Business;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
