// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  return JsxRuntime.jsx("button", {
              children: "Get Started",
              className: "" + props.styles + " bg-blue-gradient py-4 px-6 font-poppins font-medium text-[18px] outline-none text-primary"
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
