// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.bs.js";
import * as Styles from "../Styles.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import CardPng from "../assets/card.png";

var card_image = CardPng;

function CardDeal(props) {
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("h2", {
                              children: [
                                "Find a better card deal",
                                JsxRuntime.jsx("br", {
                                      className: "sm:block hidden"
                                    }),
                                "in few easy steps."
                              ],
                              className: "" + Styles.styles.heading2 + ""
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Arcu tortor, purus in mattis at sed integer faucibus. Aliquet quis\n        aliquet eget mauris tortor.ç Aliquet ultrices ac, ametau.",
                              className: "" + Styles.styles.paragraph + " max-w-[470px] mt-5"
                            }),
                        JsxRuntime.jsx(Button.make, {
                              styles: "mt-10"
                            })
                      ],
                      className: "" + Styles.layout.sectionInfo + ""
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("img", {
                            className: "w-[100%] h-[100%]",
                            alt: "billing",
                            src: card_image
                          }),
                      className: "" + Styles.layout.sectionImg + ""
                    })
              ],
              className: "" + Styles.layout.section + ""
            });
}

var make = CardDeal;

export {
  card_image ,
  make ,
}
/* card_image Not a pure module */
