// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CardDeal(props) {
  return JsxRuntime.jsx("div", {
              children: "CardDeal"
            });
}

var make = CardDeal;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
