// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Client(props) {
  return JsxRuntime.jsx("div", {
              children: "Client"
            });
}

var make = Client;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
