// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import * as Constants from "../Constants.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Client(props) {
  return JsxRuntime.jsx("section", {
              children: JsxRuntime.jsx("div", {
                    children: Constants.clients.map(function (client) {
                          return JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx("img", {
                                            className: "sm:w-[192px] w-[100px] object-contain",
                                            alt: "client_logo",
                                            src: client.logo
                                          }),
                                      className: "flex-1 " + Styles.styles.flexCenter + " sm:min-w-[192px] min-w-[120px] m-5"
                                    }, client.id);
                        }),
                    className: "" + Styles.styles.flexCenter + " flex-wrap w-full"
                  }),
              className: "" + Styles.styles.flexCenter + " my-4"
            });
}

var make = Client;

export {
  make ,
}
/* Styles Not a pure module */
