// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CTA(props) {
  return JsxRuntime.jsx("div", {
              children: "CTA"
            });
}

var make = CTA;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
