// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.bs.js";
import * as Styles from "../Styles.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function CTA(props) {
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Let's try our service now!",
                              className: "" + Styles.styles.heading2 + ""
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Everything you need to accept card payments and grow your business\n        anywhere on the planet.",
                              className: "" + Styles.styles.paragraph + " max-w-[470px] mt-5"
                            })
                      ],
                      className: "flex-1 flex flex-col"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(Button.make, {
                            styles: ""
                          }),
                      className: "" + Styles.styles.flexCenter + " sm:ml-10 ml-0 sm:mt-0 mt-10"
                    })
              ],
              className: "" + Styles.styles.flexCenter + " " + Styles.styles.marginY + " " + Styles.styles.padding + " sm:flex-row flex-col bg-black-gradient-2 rounded-[20px] box-shadow"
            });
}

var make = CTA;

export {
  make ,
}
/* Button Not a pure module */
