// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import * as Constants from "../Constants.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import LogoSvg from "../assets/logo.svg";

var logo = LogoSvg;

function Footer(props) {
  var link_mb = function (footerlink, index) {
    if (index !== (footerlink.links.length - 1 | 0)) {
      return "mb-4";
    } else {
      return "mb-0";
    }
  };
  var social_mb = function (index) {
    if (index !== (Constants.socialMedia.length - 1 | 0)) {
      return "mr-6";
    } else {
      return "mr-0";
    }
  };
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("img", {
                                      className: "w-[266px] h-[72.14px] object-contain",
                                      alt: "hoobank",
                                      src: logo
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "A new way to make the payments easy, reliable and secure.",
                                      className: "" + Styles.styles.paragraph + " mt-4 max-w-[312px]"
                                    })
                              ],
                              className: "flex-[1] flex flex-col justify-start mr-10"
                            }),
                        JsxRuntime.jsx("div", {
                              children: Constants.footerLinks.map(function (footerlink) {
                                    return JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("h4", {
                                                        children: footerlink.title,
                                                        className: "font-poppins font-medium text-[18px] leading-[27px] text-white"
                                                      }),
                                                  JsxRuntime.jsx("ul", {
                                                        children: footerlink.links.map(function (link, index) {
                                                              return JsxRuntime.jsx("li", {
                                                                          children: link.name,
                                                                          className: "" + link_mb(footerlink, index) + " font-poppins font-normal text-[16px] leading-[24px] text-dimWhite hover:text-secondary cursor-pointer"
                                                                        }, link.name);
                                                            }),
                                                        className: "list-none mt-4"
                                                      })
                                                ],
                                                className: "flex flex-col ss:my-0 my-4 min-w-[150px]"
                                              }, footerlink.title);
                                  }),
                              className: "flex-[1.5] w-full flex flex-row justify-between flex-wrap md:mt-0 mt-10"
                            })
                      ],
                      className: "" + Styles.styles.flexStart + " md:flex-row flex-col mb-8 w-full"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                              children: "Copyright Ⓒ 2022 HooBank. All Rights Reserved.",
                              className: "font-poppins font-normal text-center text-[18px] leading-[27px] text-white"
                            }),
                        JsxRuntime.jsx("div", {
                              children: Constants.socialMedia.map(function (social, index) {
                                    return JsxRuntime.jsx("img", {
                                                className: "" + social_mb(index) + " w-[21px] h-[21px] object-contain cursor-pointer",
                                                alt: social.id,
                                                src: social.icon
                                              }, social.id);
                                  }),
                              className: "flex flex-row md:mt-0 mt-6"
                            })
                      ],
                      className: "w-full flex justify-between items-center md:flex-row flex-col pt-6 border-t-[1px] border-t-[#3F3E45]"
                    })
              ],
              className: "" + Styles.styles.flexCenter + " " + Styles.styles.paddingY + " flex-col"
            });
}

var make = Footer;

export {
  logo ,
  make ,
}
/* logo Not a pure module */
