// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Footer(props) {
  return JsxRuntime.jsx("div", {
              children: "Footer"
            });
}

var make = Footer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
