// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function GetStart(props) {
  return JsxRuntime.jsx("div", {});
}

var make = GetStart;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
