// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Constants from "../Constants.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import LogoSvg from "../assets/logo.svg";
import MenuSvg from "../assets/menu.svg";
import CloseSvg from "../assets/close.svg";

var logo = LogoSvg;

var close_icon = CloseSvg;

var menu_icon = MenuSvg;

function menu(mobile) {
  var end_menu_item_margin = function (index) {
    if (mobile) {
      if ((Constants.navLinks.length - 1 | 0) === index) {
        return "mr-0";
      } else {
        return "mb-4";
      }
    } else if ((Constants.navLinks.length - 1 | 0) === index) {
      return "mr-0";
    } else {
      return "mr-10";
    }
  };
  return Constants.navLinks.map(function (nav, index) {
              return JsxRuntime.jsx("li", {
                          children: JsxRuntime.jsx("a", {
                                children: nav.title,
                                href: "" + nav.id + ""
                              }),
                          className: "" + end_menu_item_margin(index) + " font-poppins font-normal cursor-pointer text-[16px] text-white"
                        }, "" + nav.id + "");
            });
}

function Navbar(props) {
  var match = React.useState(function () {
        return false;
      });
  var setToggle = match[1];
  var toggle = match[0];
  var mobile_menu_icon = toggle ? close_icon : menu_icon;
  var mobile_menu_toggle = toggle ? "flex" : "hidden";
  return JsxRuntime.jsxs("nav", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "w-[124px] h-[32px]",
                      alt: "hoobank",
                      src: logo
                    }),
                JsxRuntime.jsx("ul", {
                      children: menu(false),
                      className: "list-none sm:flex hidden justify-end items-center flex-1"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              className: "w-[28px] h-[28px] object-contain",
                              alt: "menu",
                              src: "" + mobile_menu_icon + "",
                              onClick: (function ($$event) {
                                  Curry._1(setToggle, (function (toggle) {
                                          return !toggle;
                                        }));
                                })
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("ul", {
                                    children: menu(true),
                                    className: "list-none flex justify-end items-center flex-1 flex-col"
                                  }),
                              className: "" + mobile_menu_toggle + " p-6 bg-black-gradient absolute top-20 right-0 mx-4 my-2 min-w-[140px] rounded-xl sidebar"
                            })
                      ],
                      className: "sm:hidden flex flex-1 justify-end items-center"
                    })
              ],
              className: "w-full flex py-6 justfiy-between items-center navbar"
            });
}

var make = Navbar;

export {
  logo ,
  close_icon ,
  menu_icon ,
  menu ,
  make ,
}
/* logo Not a pure module */
