// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import * as Constants from "../Constants.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

var stats = Constants.stats.map(function (stat) {
      return JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("h4", {
                          children: stat.value,
                          className: "font-poppins font-semibold xs:text-[40px] text-[30px] xs:leading-[50px] leading-[43px] text-white"
                        }),
                    JsxRuntime.jsx("p", {
                          children: stat.title,
                          className: "font-poppins font-normal xs:text-[20px] text-[15px] xs:leading-[26px] leading-[21px] text-gradient ml-3 uppercase"
                        })
                  ],
                  className: "bg-black-gradient p-6 rounded-xl flex-1 flex justify-start items-center flex-row m-3"
                }, stat.id);
    });

function Stats(props) {
  return JsxRuntime.jsx("section", {
              children: stats,
              className: "" + Styles.styles.flexCenter + " flex-row flex-wrap sm:mb-20 mb-6"
            });
}

var make = Stats;

export {
  stats ,
  make ,
}
/* stats Not a pure module */
