// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Stats(props) {
  return JsxRuntime.jsx("div", {
              children: "Stats"
            });
}

var make = Stats;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
