// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Testimonials(props) {
  return JsxRuntime.jsx("div", {
              children: "Testimonials"
            });
}

var make = Testimonials;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
