// Generated by ReScript, PLEASE EDIT WITH CARE

import SendSvg from "./assets/Send.svg";
import StarSvg from "./assets/Star.svg";
import AirbnbSvg from "./assets/airbnb.png";
import ShieldSvg from "./assets/Shield.svg";
import BinanceSvg from "./assets/binance.png";
import DropboxSvg from "./assets/dropbox.png";
import TwitterSvg from "./assets/twitter.svg";
import CoinbaseSvg from "./assets/coinbase.png";
import FacebookSvg from "./assets/facebook.svg";
import LinkedinSvg from "./assets/linkedin.svg";
import People01Svg from "./assets/people01.png";
import People02Svg from "./assets/people02.png";
import People03Svg from "./assets/people03.png";
import InstagramSvg from "./assets/instagram.svg";

var people01 = People01Svg;

var people02 = People02Svg;

var people03 = People03Svg;

var facebook = FacebookSvg;

var instagram = InstagramSvg;

var linkedin = LinkedinSvg;

var twitter = TwitterSvg;

var airbnb = AirbnbSvg;

var binance = BinanceSvg;

var coinbase = CoinbaseSvg;

var dropbox = DropboxSvg;

var send = SendSvg;

var shield = ShieldSvg;

var star = StarSvg;

var navLinks = [
  {
    id: "home",
    title: "Home"
  },
  {
    id: "features",
    title: "Features"
  },
  {
    id: "product",
    title: "Product"
  },
  {
    id: "clients",
    title: "Clients"
  }
];

var features = [
  {
    id: "feature-1",
    icon: star,
    title: "Rewards",
    content: "The best credit cards offer some tantalizing combinations of promotions and prizes"
  },
  {
    id: "feature-2",
    icon: shield,
    title: "100% Secured",
    content: "We take proactive steps make sure your information and transactions are secure."
  },
  {
    id: "feature-3",
    icon: send,
    title: "Balance Transfer",
    content: "A balance transfer credit card can save you a lot of money in interest charges."
  }
];

var feedback = [
  {
    id: "feedback-1",
    content: "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
    name: "Herman Jensen",
    title: "Founder & Leader",
    img: people01
  },
  {
    id: "feedback-2",
    content: "Money makes your life easier. If you're lucky to have it, you're lucky.",
    name: "Steve Mark",
    title: "Founder & Leader",
    img: people02
  },
  {
    id: "feedback-3",
    content: "It is usually people in the money business, finance, and international trade that are really rich.",
    name: "Kenn Gallagher",
    title: "Founder & Leader",
    img: people03
  }
];

var stats = [
  {
    id: "stats-1",
    title: "User Active",
    value: "3800+"
  },
  {
    id: "stats-2",
    title: "Trusted by Company",
    value: "230+"
  },
  {
    id: "stats-3",
    title: "Transaction",
    value: "$230M+"
  }
];

var footerLinks = [
  {
    title: "Useful Links",
    links: [
      {
        name: "Content",
        link: "https://www.hoobank.com/content/"
      },
      {
        name: "How it Works",
        link: "https://www.hoobank.com/how-it-works/"
      },
      {
        name: "Create",
        link: "https://www.hoobank.com/create/"
      },
      {
        name: "Explore",
        link: "https://www.hoobank.com/explore/"
      },
      {
        name: "Terms & Services",
        link: "https://www.hoobank.com/terms-and-services/"
      }
    ]
  },
  {
    title: "Community",
    links: [
      {
        name: "Help Center",
        link: "https://www.hoobank.com/help-center/"
      },
      {
        name: "Partners",
        link: "https://www.hoobank.com/partners/"
      },
      {
        name: "Suggestions",
        link: "https://www.hoobank.com/suggestions/"
      },
      {
        name: "Blog",
        link: "https://www.hoobank.com/blog/"
      },
      {
        name: "Newsletters",
        link: "https://www.hoobank.com/newsletters/"
      }
    ]
  },
  {
    title: "Partner",
    links: [
      {
        name: "Our Partner",
        link: "https://www.hoobank.com/our-partner/"
      },
      {
        name: "Become a Partner",
        link: "https://www.hoobank.com/become-a-partner/"
      }
    ]
  }
];

var socialMedia = [
  {
    id: "social-media-1",
    icon: instagram,
    link: "https://www.instagram.com/"
  },
  {
    id: "social-media-2",
    icon: facebook,
    link: "https://www.facebook.com/"
  },
  {
    id: "social-media-3",
    icon: twitter,
    link: "https://www.twitter.com/"
  },
  {
    id: "social-media-4",
    icon: linkedin,
    link: "https://www.linkedin.com/"
  }
];

var clients = [
  {
    id: "client-1",
    logo: airbnb
  },
  {
    id: "client-2",
    logo: binance
  },
  {
    id: "client-3",
    logo: coinbase
  },
  {
    id: "client-4",
    logo: dropbox
  }
];

export {
  people01 ,
  people02 ,
  people03 ,
  facebook ,
  instagram ,
  linkedin ,
  twitter ,
  airbnb ,
  binance ,
  coinbase ,
  dropbox ,
  send ,
  shield ,
  star ,
  navLinks ,
  features ,
  feedback ,
  stats ,
  footerLinks ,
  socialMedia ,
  clients ,
}
/* people01 Not a pure module */
